### PR TITLE
Update linter vs. diagnostics warning

### LINKED ISSUE #17: Documentation links to Nuclide
### Description
It seems the built in documentation links are still linking to nuclide.io.

### Expected Behavior
Documentation should link to an Atom IDE page, maybe under https://atom.io/ide?

### Actual Behavior
Documentation links to nuclide.io, for example if you have `linter` enabled it shows a warning pointing you to [this page](https://nuclide.io/docs/advanced-topics/linter-package-compatibility/).

As a note, that page isn't even accurate for this package since there are no `nuclide-diagnostics-*` packages installed.

### Versions
* Atom: 1.21.0-beta0
* Nuclide: Not installed _(Why is this in the template here???)_
* Client OS: Windows 10 Enterprise x64
* Server OS (optional): _(Is this something related to Nuclide?)_

Not asked for but:
* Atom IDE version: 0.3.1

### Additional Details
<details>
<summary>Installed packages</summary>

```
Dev Packages (103) C:\Users\Landon Abney\.atom\dev\packages
├── atom-autocomplete-php@0.22.2 (disabled)
├── atom-languageclient@0.1.0
├── intentions@1.1.2
├── linter@2.2.0
├── linter-ansible-lint@0.0.7
├── linter-ansible-linting@1.2.3
├── linter-ansible-syntax@1.1.3
├── linter-bailey@0.2.2
├── linter-bootlint@1.1.0
├── linter-clang@4.1.2
├── linter-clang-check@4.1.2
├── linter-clojure@1.2.0
├── linter-codeclimate@0.2.5
├── linter-codscriptizer@0.2.0
├── linter-coffeelint@1.3.1
├── linter-cppcheck@0.2.2
├── linter-cpplint@2.0.1
├── linter-csslint@1.3.4
├── linter-dartanalyzer@0.3.2
├── linter-docker@0.2.1
├── linter-elixirc@1.7.0
├── linter-erb@1.1.0
├── linter-erlc@0.4.0
├── linter-eslint@8.2.1
├── linter-flake8@2.2.1
├── linter-flexpmd@0.1.9
├── linter-flint@1.0.1
├── linter-flow@5.6.1
├── linter-foodcritic@0.5.4
├── linter-gettext@0.1.3
├── linter-gfortran@0.5.0
├── linter-gjslint@1.5.2
├── linter-glsl@2.1.3
├── linter-golinter@1.2.2
├── linter-gotype@0.1.0
├── linter-govet@0.1.5
├── linter-haml@2.0.2
├── linter-harbour@6.6.1
├── linter-hlint@2.0.0
├── linter-htmlhint@1.3.3
├── linter-icinga-validate@1.0.0
├── linter-javac@1.9.4
├── linter-jolie@0.7.1
├── linter-js-yaml@1.2.7
├── linter-jscs@4.1.3 (disabled)
├── linter-jshint@3.1.5
├── linter-jsl@0.0.1
├── linter-jsonlint@1.3.0
├── linter-kibit@0.0.1
├── linter-lintr@1.1.4
├── linter-lsc@2.4.0
├── linter-lua@1.0.2
├── linter-luacheck@2.0.1
├── linter-markdown@5.2.0
├── linter-moonscript@1.1.1
├── linter-oclitnt@0.0.3
├── linter-packer-validate@1.0.1
├── linter-perl@0.8.0
├── linter-perlcritic@1.4.2
├── linter-php@1.4.0
├── linter-phpcs@1.6.7
├── linter-phplint@0.1.0
├── linter-phpmd@1.5.3
├── linter-proselint@3.3.0
├── linter-pug@1.3.1
├── linter-puppet-lint@0.8.2
├── linter-puppet-parsing@1.0.4
├── linter-pycodestyle@2.1.3
├── linter-pydocstyle@0.4.6
├── linter-pyflakes@0.3.2
├── linter-pylama@0.9.2
├── linter-pylint@2.1.0
├── linter-reek@2.2.2
├── linter-roodi@1.1.0
├── linter-rst@0.0.3
├── linter-rubocop@2.1.1
├── linter-ruby@1.2.6
├── linter-ruby-lint@1.2.0
├── linter-rust@0.8.0
├── linter-sass-lint@1.7.6
├── linter-scalac@1.4.4
├── linter-scalastyle@1.4.1
├── linter-scss-lint@3.1.1
├── linter-shellcheck@1.4.6
├── linter-slim@1.0.0
├── linter-spell@0.13.2
├── linter-spell-html@0.6.1
├── linter-spell-javascript@0.7.1
├── linter-spell-latex@0.9.1
├── linter-spell-project@0.1.3
├── linter-spell-ruby@0.3.1
├── linter-stylelint@4.0.2
├── linter-stylint@2.2.8
├── linter-swagger@0.4.2
├── linter-swiftc@2.0.0
├── linter-swiftlint@1.2.2
├── linter-terraform-syntax@1.1.1
├── linter-tidy@2.3.1
├── linter-tslint@1.7.0
├── linter-ui-default@1.6.8
├── linter-xmllint@1.4.1
├── minimap-linter@2.0.2
└── squirrel-linter@0.3.3

Community Packages (102) C:\Users\Landon Abney\.atom\packages
├── atom-autocomplete-php@0.25.6 (disabled)
├── atom-beautify@0.30.5
├── atom-ide-ui@0.3.1
├── atom-jade@0.3.0
├── atom-material-syntax@1.0.6
├── atom-material-syntax-dark@1.0.0
├── atom-material-syntax-light@0.4.6
├── atom-material-ui@2.0.4
├── atom-typescript@11.0.8 (disabled)
├── autocomplete-lua@0.8.3
├── busy-signal@1.4.3
├── docblockr@0.11.0
├── editorconfig@2.2.2
├── file-watcher@1.2.6
├── fizzy@0.21.0
├── flow-ide@1.8.1 (disabled)
├── highlight-selected@0.13.1
├── hyperclick@0.1.5 (disabled)
├── ide-flowtype@0.17.0
├── ide-php@0.6.1
├── ide-typescript@0.6.1
├── intentions@1.1.5
├── language-ansible@0.2.1
├── language-babel@2.74.1 (disabled)
├── language-chef@0.10.0
├── language-cjson@0.0.1
├── language-docker@1.1.8
├── language-elixir@0.20.2
├── language-erlang@3.2.0
├── language-fortran@2.1.6
├── language-gettext@0.6.1
├── language-glsl@2.0.1
├── language-haml@0.25.1
├── language-haskell@1.13.2
├── language-icinga2@0.3.0
├── language-ini@1.19.0
├── language-jade@0.7.2
├── language-jolie@0.5.0
├── language-kotlin@0.5.0
├── language-livescript@0.0.3
├── language-lua@0.9.11
├── language-moonscript@1.7.1
├── language-postcss@1.3.1
├── language-powershell@4.0.0
├── language-puppet@0.23.0
├── language-r@0.4.2
├── language-reg@0.0.0
├── language-rust@0.4.12
├── language-swift@0.5.0
├── language-terraform@0.8.1
├── language-vue@0.23.1
├── linter@2.2.0
├── linter-alex@4.0.0
├── linter-clang@4.1.2
├── linter-coffeelint@1.3.1
├── linter-csslint@2.0.0
├── linter-eslint@8.2.1
├── linter-flake8@2.2.1
├── linter-htmlhint@1.3.3
├── linter-js-standard@4.0.1
├── linter-js-yaml@1.2.7
├── linter-jshint@3.1.5
├── linter-jsonlint@1.3.0
├── linter-markdown@5.2.0
├── linter-perl@0.8.1
├── linter-perlcritic@1.4.2
├── linter-php@1.4.0
├── linter-phpcs@1.6.7
├── linter-phpmd@1.5.3
├── linter-proselint@3.3.0
├── linter-pylama@0.9.4
├── linter-pylint@2.1.0
├── linter-rails-best-practices@0.2.2 (disabled)
├── linter-reek@2.2.2
├── linter-rubocop@2.1.1
├── linter-ruby@1.2.6
├── linter-stylelint@4.0.2
├── linter-tidy@2.3.1
├── linter-ui-default@1.6.8
├── linter-ui-plus@0.3.2 (disabled)
├── mapfile-grammar@0.1.0
├── merge-conflicts@1.4.5 (disabled)
├── minimap@4.29.6
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-linter@2.0.2
├── minimap-selection@4.5.0
├── monokai@0.24.0
├── nord-atom-syntax@0.9.1
├── nord-atom-ui@0.11.0
├── pigments@0.40.2
├── preview-inline@1.4.7
├── sequential-number@0.5.0
├── seti-syntax@1.1.3
├── seti-ui@1.9.0
├── sort-lines@0.15.0
├── Stylus@3.1.1
├── svn@0.0.13 (disabled)
├── tab-control@0.6.10
├── toggle-quotes@1.0.1
├── town-crier@0.2.1
└── trailing-spaces@0.4.0
```
</details>

### PR DESCRIPTION
**Pull request by hansonw**
This removes the link to the docs and uses a notification to display the warning.
Now, users have the option of disabling either the linter or diagnostics packages.

screen shot 2017-09-14 at 3 22 27 pm

Fixes #17 (cc @Arcanemagus)

### CODE REVIEW

**Comment by Arcanemagus** [comment]
The only comment I have here is that `atom-ide-diagnostics` is only obvious as not being a separate package if you have already looked through the settings for `atom-ide-ui`. On the other hand, since `atom-ide-ui` contains many smaller parts I'm not sure of a better way to say that.

**Comment by mehcode** [comment]
@hansonw Strongly dislike this in the panel. I'd rather this be a warning notification that re-occurs on a fresh atom instance.

**Comment by hansonw** [comment]
@mehcode do you leave both linter and diagnostics on? I'm not sure how it's too different - the intention is that you resolve this ASAP

**Comment by mehcode** [comment]
Coming from a UX perspective, the key point here is it's what people _expect_. Atom has a standard system for delivering warnings about the environment. This is strictly that and should not be delivered in another medium.

---

Another win is that there isn't nearly as much code-to-maintain behind it as its in Atom core.

**Comment by Arcanemagus** [comment]
That's a _much_ better fit into Atom's setup, thanks for bringing that up @mehcode!

**Pull request merged**
