### PR TITLE
added show on cursor over for datatip

### PR DESCRIPTION
**Pull request by udnaan**
This takes care of #112 

Overall it turned out to be a minor change and should not cause any regression or breakage.

### CODE REVIEW

**Comment by udnaan** [comment]
Any chance of this being merged soon?

**Comment by pelmers** [comment]
Hey @udnaan  sorry about the delay -- unfortunately we're not able to import the pull request from this repository. Could you re-submit on https://github.com/facebook/nuclide ?

The file paths are the same, just replace `atom-ide-ui` with `nuclide`

**Comment by udnaan** [comment]
Sure. Done

**Comment by pelmers** [comment]
thanks!

**Pull request closed without merging**
